### ISSUE TITLE
Working Width

### ISSUE THREAD

**Issue by Jayshua83** [ZhooL/FS22_EnhancedVehicle#100]
Where does Enhanced Vehicle calculate Working Width from?

I have several mods where I have to manually set up the WW in EV because they come up incorrectly, but if I know where it calculates it based on I might be able to edit the xml and set the WW correctly?

**Comment by ZhooL** [comment]
Hi, the WW is calculated by difference between the left & right AI Markers. If no AI Markers are present (which should be; otherwise the AI could not properly use the attachment) I try to calculate the WW using the sizes of the workareas. Code for that is starting around line 2190 in FS22_EnhancedVehicle.lua
